name: Publisher

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run script
        env:
          REPO_TOKEN: ${{ secrets.CQDG_FHIR_DEPLOY_KEY }}
        run: |
          chmod u+x .github/build.sh
          .github/build.sh
