name: Publisher

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Run script
        env:
          REPO_TOKEN: ${{ secrets.CQDG_FHIR_DEPLOY_KEY }}
        run: |
          chmod u+x .github/build.sh
          .github/build.sh
